#1158 Ketcher needs to correctly serialize/deserialize attachment point information for super atoms for mol v3000 & ket format
epam/Indigo pull request #1163
Opened 2023-06-28 08:34 UTC by Wadym

2023-06-29 13:33 UTC, AlexanderSavelyev requested changes

2023-06-30 10:53 UTC, Wadym commented on core/indigo-core/molecule/src/molecule_json_loader.cpp
> +                    std::string id = attachmentPoints[j]["attachmentId"].GetString();
Done

2023-06-30 11:09 UTC, Wadym commented on api/tests/integration/tests/formats/serialize_deserialize_attachment_points_in_ket.py
> +    # print(ket_in.json())
Done

2023-06-30 12:08 UTC, Wadym commented
https://github.com/epam/Indigo/pull/1163/checks contains that PR has been checked (here the same commit has been checked https://github.com/epam/Indigo/actions/runs/5422196571)

2023-07-03 10:13 UTC, AlexanderSavelyev approved these changes

2023-07-03 10:13 UTC, merged