Issue #731 Structure Check doesn't work for R-Groups
epam/Indigo pull request #1177
Opened 2023-07-17 20:13 UTC by AliaksandrDziarkach

Update StructureChecker::checkMolecule to check content of R-Groups.
Into StructureChecker::CheckMessage added field "prefix" to store checked R-group to which message related.
Updated C-api dumpMessage to add prefix into json. Added UTs to indigo-core-unit-tests.
Added UTs to integration tests.

2023-07-18 08:35 UTC, AlexanderSavelyev requested changes

2023-07-18 08:35 UTC, AlexanderSavelyev commented on api/tests/integration/ref/check/check-issue731.py.out
> +Result: {"rgroups":"Structure contains R-groups","3d":"R20:Structure contains 3D coordinates: (0,1,2,3,4,5)"}
please add "R-Group R#" as a prefix

2023-07-18 08:35 UTC, AlexanderSavelyev commented on core/indigo-core/molecule/src/structure_checker.cpp
> +        std::string prefix = "R" + std::to_string(idx);
please add "R-Group R" + to_string(idx) as a prefix

2023-07-18 09:44 UTC, AliaksandrDziarkach commented on api/tests/integration/ref/check/check-issue731.py.out
> +Result: {"rgroups":"Structure contains R-groups","3d":"R20:Structure contains 3D coordinates: (0,1,2,3,4,5)"}
Fixed

2023-07-19 10:27 UTC, AlexanderSavelyev approved these changes

2023-07-19 10:29 UTC, merged