#1040 SMILES/SMARTS import: Files with S-Group cause an error
epam/Indigo pull request #1201
Opened 2023-07-26 15:51 UTC by AliaksandrDziarkach

Implemented import support for Data S-Groups.
 Implemented import support for all fields for Polymer S-Groups.
 Implemented export support for Data S-Groups.
 Implemented export support for all fields for Polymer S-Groups.
 Implemented corresponding UTs into indigo-core-unit-tests.
 Fix integration UTs.

2023-07-27 07:57 UTC, AlexanderSavelyev requested changes

2023-07-27 07:57 UTC, AlexanderSavelyev commented on core/indigo-core/molecule/src/smiles_loader.cpp
> +        if (code >= 0 && code < 256 && scanner.lookNext() == ';')
please move the 256 to a constant

2023-07-27 07:57 UTC, AlexanderSavelyev commented on core/indigo-core/molecule/src/smiles_loader.cpp
> +                if (_scanner.length() - pos >= 4)
please move 4 to the constant

2023-07-27 07:57 UTC, AlexanderSavelyev commented on core/indigo-core/molecule/src/smiles_loader.cpp
> +                    char buf[5];
5 to the constant

2023-07-27 07:57 UTC, AlexanderSavelyev commented on core/indigo-core/molecule/src/smiles_loader.cpp
> +                char pchar_sg_type[3];
add constant for 3 (is it max sgroup name len?)

2023-07-27 07:57 UTC, AlexanderSavelyev commented on core/indigo-core/molecule/src/smiles_loader.cpp
> +                if (count < 8)
move 8 to constants

2023-07-31 13:19 UTC, even1024 approved these changes

2023-07-31 14:11 UTC, merged