#1592 Macro: V3000 Export: Complex structure (modified RNA-peptide-disulfide bridge) saved to mol V3000 is displayed improperly in other sketcher (part of the structure left)
epam/Indigo pull request #1735
Opened 2024-02-21 11:01 UTC by even1024

## Remove-me-section
* Notify reviewers about the pull request
* Keep only necessary sections below for the review

## Generic request
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name does not contain '#'
- [ ] base branch (master or release/xx) is correct
- [ ] PR is linked with the issue
- [ ] task status changed to "Code review"
- [ ] code follows product standards
- [ ] regression tests updated
### For release/xx branch
- [ ] backmerge to master (or newer release/xx) branch is created
### Optional
- [ ] unit-tests written
- [ ] documentation updated

## Backmerge request
- [ ] PR name follows the pattern `Backmerge: #1234 – issue name`
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] code contains only backmerge changes

## Bump request
- [ ] PR name follows the pattern `Bump version to ...`
- [ ] add brackets \[ \] for 'skip ci' and put it into the body
- [ ] all tickets are closed inside the relevant milestone

2024-02-26 12:18 UTC, AlexanderSavelyev requested changes

2024-02-27 08:45 UTC, even1024 commented on api/tests/integration/tests/formats/ref/conjugate.seq
> -DEFGHIKUVCEFGUVCUVIK
Everything is correct.

DEFGHIKUVCEFGUVCUVIK
TGGCGTACTCACCAGTCGCCGC

changed to:

TGGCGTACTCACCAGTCGCCGC
DEFGHIKUVCEFGUVCUVIK


![image](https://github.com/epam/Indigo/assets/7814977/96aff600-c161-451e-a27c-ee6c255ce1d7)

2024-02-27 09:46 UTC, even1024 commented on api/tests/integration/tests/formats/ref/all_aminoacids.ket
> -            "y": 0.0
-0.0 is a part of [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754)
there is no difference in behaviour of -0.0 and +0.0. Result of comparison of -0.0 and +0.0 is true.

2024-02-27 09:57 UTC, AlexanderSavelyev approved these changes

2024-02-27 11:23 UTC, AliaksandrDziarkach approved these changes
LGTM

2024-02-28 07:43 UTC, merged