#2236 Import/export multi-tails in KET
epam/Indigo pull request #2295
Opened 2024-09-03 17:24 UTC by even1024

## Generic request
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name does not contain '#'
- [x] base branch (master or release/xx) is correct
- [x] PR is linked with the issue
- [x] task status changed to "Code review"
- [x] code follows product standards
- [x] regression tests updated

2024-09-03 18:52 UTC, AlexanderSavelyev requested changes

2024-09-03 18:52 UTC, AlexanderSavelyev commented on core/indigo-core/reaction/src/reaction_multistep_detector.cpp
> +    rapidjson::StringBuffer buffer;
why json saver in multistep detector?

2024-09-03 19:18 UTC, even1024 commented on core/indigo-core/layout/pathway_layout.h
> +                number = -2;
changed to -1. (non initialized)

2024-09-03 19:19 UTC, even1024 commented on core/indigo-core/reaction/src/reaction_multistep_detector.cpp
> +    rapidjson::StringBuffer buffer;
removed debug code

2024-09-04 15:33 UTC, AlexanderSavelyev approved these changes

2024-09-04 17:03 UTC, merged