2404 ket to rdf
epam/Indigo pull request #2640
Opened 2024-11-18 09:33 UTC by even1024

## Generic request
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name does not contain '#'
- [x] base branch (master or release/xx) is correct
- [x] PR is linked with the issue
- [x] task status changed to "Code review"
- [x] code follows product standards
- [x] regression tests updated

2024-11-22 09:48 UTC, AlexanderSavelyev requested changes

2024-11-22 09:48 UTC, AlexanderSavelyev commented on core/indigo-core/layout/src/pathway_layout.cpp
> +        if (std::round(height * 1000) >= std::round(_text_line_height * 1000))
add constant for 1000

2024-11-22 09:48 UTC, AlexanderSavelyev commented on core/indigo-core/layout/src/pathway_layout.cpp
> +            if (std::round(height * 1000) < std::round(_text_line_height * 1000) && props.size() - i > 1)
add constant for 1000

2024-11-22 23:50 UTC, even1024 commented on core/indigo-core/layout/src/pathway_layout.cpp
> +            if (std::round(height * 1000) < std::round(_text_line_height * 1000) && props.size() - i > 1)
fixed

2024-11-22 23:50 UTC, even1024 commented on core/indigo-core/layout/src/pathway_layout.cpp
> +        if (std::round(height * 1000) >= std::round(_text_line_height * 1000))
fixed

2024-11-25 09:06 UTC, AlexanderSavelyev approved these changes

2024-11-25 09:07 UTC, merged