WIP: Feature/bingo elastic reactions
epam/Indigo pull request #274
Opened 2020-12-26 14:03 UTC by khyurri

This PR adds reaction support to python bingo-elastic implementation

What changed:

1. Instance of IndigoRecord class cannot be saved to Elasticsearch. Developer must create instance of IndigoRecordMolecule or IndigoRecordReaction for saving to Elasticsearch.
2. Index bingo renamed to bingo-molecule. Added index bingo-reaction
3. Developer must provide index when creates an instance of ElasticRepository

2021-01-07 19:43 UTC, MysterionRise requested changes
Overall, I would like to discuss those changes and ultimately I'm keen to have it differently than enums, but should be open for discussion

2021-01-07 19:43 UTC, MysterionRise commented on api/plugins/bingo-elastic/java/src/main/java/com/epam/indigo/elastic/ElasticRepository.java
> +            operations.add(repo -> repo.indexName = (new IndexName(indexName)).toString());
why you need to copy constructor here?

2021-01-07 19:43 UTC, MysterionRise commented on api/plugins/bingo-elastic/java/src/main/java/com/epam/indigo/elastic/IndexName.java
> +        return this.index.toString().toLowerCase();
if you want to do to string - you may do custom toString for Enum to provide name friendly representation.

2021-01-07 19:43 UTC, MysterionRise commented on api/plugins/bingo-elastic/java/src/test/java/com/epam/indigo/elastic/ElasticRepositoryTest.java
> +
Empty test?

2021-01-20 17:07 UTC, MysterionRise approved these changes
In general, I'm good, will update some Java code with code from #251

2021-01-20 17:07 UTC, MysterionRise commented on api/plugins/bingo-elastic/java/src/main/java/com/epam/indigo/elastic/IndexName.java
> +    public static final String BINGO_REACTION = "bingo_reactions";
forgot to rename constants name to BINGO_MOLECULES

2021-01-20 17:07 UTC, MysterionRise commented on api/plugins/bingo-elastic/python/bingo_elastic/elastic.py
> +    BINGO_REACTION = "bingo-reactions"
same here

2021-01-28 10:32 UTC, MysterionRise commented on api/plugins/bingo-elastic/java/src/test/java/com/epam/indigo/elastic/FullUsageMoleculeTest.java
> +
Empty test for now?

2021-01-29 21:20 UTC, khyurri commented
Java and Python versions are ready for review

2021-01-30 05:26 UTC, MysterionRise approved these changes

2021-01-30 14:08 UTC, mkviatkovskii approved these changes

2021-01-30 14:08 UTC, mkviatkovskii commented
I see some tests are still failing. We can merge the request after fixing that.

2021-01-31 13:19 UTC, merged