CDXML format support
epam/Indigo pull request #536
Opened 2021-11-23 06:58 UTC by even1024

All basic features and fragments' connections supported.

2021-11-23 10:12 UTC, mkviatkovskii commented on utils/indigo-depict/main.c
> +            indigoLayout(obj);
Why do we need to layout in this case? We layout in other branch of condition.

2021-11-23 10:13 UTC, mkviatkovskii commented on utils/indigo-depict/main.c
> +    indigoSetOption("molfile-saving-mode", "3000");
This change also looks pretty strange, do we really need it?

2021-11-23 10:15 UTC, mkviatkovskii requested changes
We also need to add tests for CDXML loader, don't see any.

2021-11-23 14:04 UTC, mkviatkovskii approved these changes

2021-11-23 23:35 UTC, SunFellow commented on api/tests/integration/tests/formats/cdxml_to_mol.py
> +        mol = indigo.loadQueryMoleculeFromFile(os.path.join(root, filename))
Why not to catch and print exception here as well? Even caught the exception can fail the test.
In addition, maybe it makes sense to complete the cycle by files to get whole diagnostics?

2021-11-24 00:01 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +    struct _ExtConnection
Please check the naming style: underscore is usually used for inner protected types. But here `struct _ExtConnection` is independent (not a subclass), exposed in the header, thus it's quite public.

2021-11-24 00:54 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        int type;
is not initialized by default. (is not assigned in constructor and does not have own default constructor)

2021-11-24 00:54 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        bool is_not_list;
is not initialized by default. (is not assigned in constructor and does not have own default constructor)

2021-11-24 00:54 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        bool swap_bond;
is not initialized by default. (is not assigned in constructor and does not have own default constructor)

2021-11-24 00:55 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        int usage;
is not initialized by default. (is not assigned in constructor and does not have own default constructor)

2021-11-24 00:56 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +    }
IMHO, this is auxiliary function and should not be exposed in the header.

2021-11-24 00:56 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        MoleculeCdxmlLoader(const MoleculeCdxmlLoader&); // no implicit copy
`= delete;`

2021-11-24 00:57 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        QueryMolecule* _pqmol;
It makes sense to initialize them by default with null_ptr-s

2021-11-24 01:42 UTC, SunFellow commented on core/indigo-core/molecule/src/molecule_cdxml_loader.cpp
> +            throw Error("Not enought coordinates for atom position");
Mistype: `enought`

2021-11-24 01:46 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        bool _has_bounding_box;
is not initialized by default. (is not assigned in constructor and does not have own default constructor)

2021-11-24 02:19 UTC, SunFellow commented on core/indigo-core/molecule/src/molecule_cdxml_loader.cpp
> +        _pmol->setIgnoreBadValenceFlag(ignore_bad_valence);
Passing a variable that was never initialized or assigned.

2021-11-24 02:39 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        void _applyDispatcher(TiXmlAttribute* pAttr, const std::unordered_map<std::string, std::function<void(std::string&)>>& dispatcher);
Such a wordy type (`std::unordered_map<std::string, std::function<void(std::string&)>>& dispatcher`) is worth using or typedef.

2021-11-24 02:44 UTC, SunFellow commented on core/indigo-core/molecule/molecule_cdxml_loader.h
> +        int usage;
'usage' essentially has `enum CDXBracketUsage` type. Better utilize C++ strong typing.

2021-11-24 11:08 UTC, merged