#613 Implement atom orbital hybridization computation
epam/Indigo pull request #652
Opened 2022-02-09 13:12 UTC by suppnova

2022-02-15 21:39 UTC, mkviatkovskii commented on api/python/indigo/hybridization.py
> +        return cardon_hybridization(atom)
carBon

2022-02-15 21:41 UTC, mkviatkovskii commented on api/python/indigo/hybridization.py
> +            "Hybridization is not calculated for atomic number >= 57"
"Hybridization calculation is not implemented for atomic numbers >= 57"

2022-02-15 21:41 UTC, mkviatkovskii commented on api/python/indigo/hybridization.py
> +def in_aromatic_ring(atom):
Please add type hints

2022-02-15 21:44 UTC, mkviatkovskii requested changes
Looks impressive, thanks!

Left some cosmetic related comments, and also just a thought — maybe we also need to add an Enum for hybridization types and operate with it. And add two methods:

getHybridization -> Enum
getHybridizationStr -> str

This could simplify using hybridization in ML featurization and also avoid possible mistakes with operating with raw strings. What do you think?

2022-02-16 10:15 UTC, mkviatkovskii commented on api/python/indigo/hybridization.py
> +class EnumHybridizations(Enum):
Let's rename it to HybridizationType.

2022-02-16 10:24 UTC, suppnova commented on api/python/indigo/hybridization.py
> +class EnumHybridizations(Enum):
Done

2022-02-16 11:36 UTC, mkviatkovskii approved these changes

2022-02-16 11:39 UTC, mkviatkovskii approved these changes

2022-02-16 14:41 UTC, merged